[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar build/libs/monkey_dev-0.0.1-SNAPSHOT.jar"   
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
